name: Python Code Quality
on: [ push ]
jobs:
  lock_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv lock --locked

  linting: # Code quality standards check
    runs-on: ubuntu-latest
    needs: lock_file # Ensure the lock_file job runs first
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uvx ruff check .

  formatting_ruff: # Check visual structure of code
    runs-on: ubuntu-latest
    needs: lock_file
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uvx ruff format --check .

  formatting_black:
    runs-on: ubuntu-latest
    needs: lock_file
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv run black .

  typing_mypy: # Check for type errors
    runs-on: ubuntu-latest
    needs: lock_file
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv run mypy .

  typing_pyright:
    runs-on: ubuntu-latest
    needs: lock_file
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv run pyright .

  test:
    runs-on: ubuntu-latest
    needs: [ linting, formatting_black, formatting_ruff, typing_mypy, typing_pyright ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv run pytest -v --durations=0

  build:
    runs-on: ubuntu-latest
    needs: [ linting, formatting_black, formatting_ruff, typing_mypy, typing_pyright ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv build
