name: Python Code Quality
on: [ push ]
jobs:
  lock_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv lock --locked

  linting: # Code quality standards check
    runs-on: ubuntu-latest
    needs: lock_file # Ensure the lock_file job runs first
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uvx ruff check .
  formatting: # Check visual structure of code
    runs-on: ubuntu-latest
    needs: lock_file
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uvx ruff format --check .
  typing_mypy: # Check for type errors
    runs-on: ubuntu-latest
    needs: lock_file
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv run mypy .
  typing_pyright:
    runs-on: ubuntu-latest
    needs: lock_file
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv run pyright .